### ISSUE TITLE
页面对应的数据接口服务是在smqtt那个项目里面吗？好像没找到，能否帮忙指出，谢谢！

### ISSUE THREAD

**Issue by leafseelight** [quickmsg/smqtt-ui#1]
为博主的开源精神点赞！

**Comment by CrazyBeginner** [comment]
是在smqtt的smqtt-core模块里， 包io.github.quickmsg.core.http

**Comment by leafseelight** [comment]
不好意思，再麻烦下，我找不到，比如登录页的接口，dev-api/auth/login和dev-api/code

**Comment by leafseelight** [comment]
或者说不登录的话，有办法直接看到后台的页面吗？

**Comment by leafseelight** [comment]
![image](https://user-images.githubusercontent.com/11920918/120963363-06e9b980-c794-11eb-907d-cbb7dacb1dbf.png)

**Comment by 1ssqq1lxr** [comment]
ui页面还未开发好

**Comment by leafseelight** [comment]
好的，谢谢！
